apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-server
  name: prometheus-deployment
  namespace: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-server